<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>NexClip_Setup</AssemblyName>
    <RootNamespace>NexClip.Installer</RootNamespace>
    <ApplicationIcon>..\Assets\icon.ico</ApplicationIcon>
    <Version>20260825.02</Version>
    <AssemblyVersion>2026.8.25.2</AssemblyVersion>
    <FileVersion>2026.8.25.2</FileVersion>
    <InformationalVersion>20260825.02</InformationalVersion>
    
    <!-- 单文件轻量框架依赖编译配置 (不内置庞大运行库，按需在线获取) -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\payload.zip" Condition="Exists('Resources\payload.zip')" />
    <Resource Include="..\Assets\icon.ico">
      <Link>Resources\icon.ico</Link>
    </Resource>
  </ItemGroup>

</Project>
