# 插件与依赖版本目录
[versions]
agp = "8.13.2"
kotlin = "2.4.10"
compose-bom = "2026.06.01"
activity-compose = "1.10.1"
libxposed-api = "102.0.0"
miuix = "0.9.3"
okhttp = "4.12.0"
signalr = "9.0.1"
kotlinx-coroutines = "1.10.2"
core-ktx = "1.15.0"
lifecycle-runtime = "2.8.7"
navigationevent = "1.1.2"
compose-icons = "2.2.1"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }


androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
signalr = { group = "com.microsoft.signalr", name = "signalr", version.ref = "signalr" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposed-api" }
miuix-ui = { group = "top.yukonga.miuix.kmp", name = "miuix-ui-android", version.ref = "miuix" }
miuix-icons = { group = "top.yukonga.miuix.kmp", name = "miuix-icons-android", version.ref = "miuix" }
miuix-preference = { group = "top.yukonga.miuix.kmp", name = "miuix-preference-android", version.ref = "miuix" }
miuix-blur = { group = "top.yukonga.miuix.kmp", name = "miuix-blur-android", version.ref = "miuix" }
navigationevent-compose = { group = "androidx.navigationevent", name = "navigationevent-compose-android", version.ref = "navigationevent" }
tabler-icons-outline = { group = "com.composables", name = "icons-tabler-outline-cmp", version.ref = "compose-icons" }
tabler-icons-filled = { group = "com.composables", name = "icons-tabler-filled-cmp", version.ref = "compose-icons" }
